### ISSUE TITLE
minitouch can not run in android 14（not root），Does anyone know how to solve it?

### ISSUE THREAD

**Issue by summerlife** [DeviceFarmer/minitouch#17]
minitouch cannot be used on non-rooted Android 14 models and will report a permission error. How can I solve it?
The error message is as follows：

open: Permission denied
Unable to open device /dev/input/event0 for inspectionopen: Permission denied
Unable to open device /dev/input/mice for inspectionopen: Permission denied
Unable to open device /dev/input/mouse1 for inspectionopen: Permission denied
Unable to open device /dev/input/event5 for inspectionopen: Permission denied
Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied
Unable to open device /dev/input/event2 for inspectionopen: Permission denied
Unable to open device /dev/input/event3 for inspectionopen: Permission denied
Unable to open device /dev/input/event1 for inspectionopen: Permission denied
Unable to open device /dev/input/event4 for inspectionUnable to find a suitable touch device
connecting socket: Connection refused

**Comment by KishanDasani** [comment]
I am facing some similar issue as well, using minitouch with stf and due to this issue, touch is not working in remote device.

**Comment by jerimiah797** [comment]
I'm also seeing a problem with minitouch on Android 14, though it is different. Frustratingly, it only started occurring after I upgraded from a 6-month old installation.. (unsure which version number). 

```local-provider_1  | 2024-10-15T20:52:32.311Z INF/provider 1 [*] Restarting device worker "R3CR40LK2LJ"                                                                                                                                                            
local-provider_1  | 2024-10-15T20:52:33.052Z INF/device:support:push 486 [R3CR40LK2LJ] Sending output to "tcp://stf.hq.groundspeak.biz:7270"                                                                                                                      
local-provider_1  | 2024-10-15T20:52:33.055Z INF/device 486 [R3CR40LK2LJ] Preparing device                                                                                                                                                                        
local-provider_1  | 2024-10-15T20:52:33.378Z INF/device:support:sub 486 [R3CR40LK2LJ] Receiving input from "tcp://stf.hq.groundspeak.biz:7250"                                                                                                                    
local-provider_1  | 2024-10-15T20:52:33.379Z INF/device:support:sub 486 [R3CR40LK2LJ] Subscribing to permanent channel "*ALL"                                                                                                                                     
local-provider_1  | 2024-10-15T20:52:33.464Z INF/device:support:properties 486 [R3CR40LK2LJ] Loading properties                                                                                                                                                   
local-provider_1  | 2024-10-15T20:52:33.540Z INF/device:support:sdk 486 [R3CR40LK2LJ] Supports SDK 34                                                                                                                                                             
local-provider_1  | 2024-10-15T20:52:33.542Z INF/device:support:abi 486 [R3CR40LK2LJ] Supports ABIs arm64-v8a, armeabi-v7a, armeabi                                                                                                                               
local-provider_1  | 2024-10-15T20:52:33.810Z INF/device:resources:minicap 486 [R3CR40LK2LJ] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/noarch/minicap.apk" as "/data/local/tmp/minicap.apk"                                            
local-provider_1  | 2024-10-15T20:52:34.477Z INF/device:resources:service 486 [R3CR40LK2LJ] Checking whether we need to install STFService                                                                                                                        
local-provider_1  | 2024-10-15T20:52:34.558Z INF/device:resources:service 486 [R3CR40LK2LJ] Running version check                                                                                                                                                 
local-provider_1  | 2024-10-15T20:52:35.618Z INF/device:resources:service 486 [R3CR40LK2LJ] STFService up to date                                                                                                                                                 
local-provider_1  | 2024-10-15T20:52:35.620Z INF/device:plugins:service 486 [R3CR40LK2LJ] Launching agent                                                                                                                                                         
local-provider_1  | 2024-10-15T20:52:36.139Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "Starting minitouch agent"                                                                                                                                  
local-provider_1  | 2024-10-15T20:52:36.142Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "java.lang.NoSuchMethodException: android.view.IWindowManager$Stub$Proxy.injectKeyEvent [class android.view.KeyEvent, boolean]"                             
local-provider_1  | 2024-10-15T20:52:36.143Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at java.lang.Class.getMethod(Class.java:2937)"                                                                                                             
local-provider_1  | 2024-10-15T20:52:36.145Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at java.lang.Class.getMethod(Class.java:2449)"                                                                                                             
local-provider_1  | 2024-10-15T20:52:36.146Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at jp.co.cyberagent.stf.compat.InputManagerWrapper$WindowManagerEventInjector.<init>(InputManagerWrapper.java:93)"                                         
local-provider_1  | 2024-10-15T20:52:36.147Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at jp.co.cyberagent.stf.compat.InputManagerWrapper.<init>(InputManagerWrapper.java:19)"                                                                    
local-provider_1  | 2024-10-15T20:52:36.148Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at jp.co.cyberagent.stf.MinitouchAgent.<init>(MinitouchAgent.java:288)"                                                                                    
local-provider_1  | 2024-10-15T20:52:36.149Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at jp.co.cyberagent.stf.Agent.main(Agent.java:65)"                                                                                                         
local-provider_1  | 2024-10-15T20:52:36.150Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)"                                                                                    
local-provider_1  | 2024-10-15T20:52:36.151Z INF/device:plugins:service 486 [R3CR40LK2LJ] Agent says: "at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:385)"                                                                                         
local-provider_1  | 2024-10-15T20:52:37.683Z INF/provider 1 [*] Providing 16 of 17 device(s); waiting for "R3CR40LK2LJ"                                                                                                                                           
local-provider_1  | 2024-10-15T20:52:45.944Z FTL/device 486 [R3CR40LK2LJ] Setup had an error TimeoutError: operation timed out                                                                                                                                    
local-provider_1  |     at afterTimeout (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:11:15)                                                                                                                                    
local-provider_1  |     at Timeout.timeoutTimeout [as _onTimeout] (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/timers.js:53:9)                                                                                                           
local-provider_1  |     at listOnTimeout (node:internal/timers:559:17)                                                                                                                                                                                            
local-provider_1  |     at processTimers (node:internal/timers:502:7)                                                                                                                                                                                             
local-provider_1  | 2024-10-15T20:52:45.945Z FTL/util:lifecycle 486 [R3CR40LK2LJ] Shutting down due to fatal error                                                                                                                                                
local-provider_1  | 2024-10-15T20:52:45.955Z INF/provider 1 [*] Cleaning up device worker "R3CR40LK2LJ"                                                                                                                                                           
local-provider_1  | 2024-10-15T20:52:45.955Z ERR/provider 1 [*] Device worker "R3CR40LK2LJ" died with code 1 ```

**Comment by here101** [comment]
+1

**Comment by WINGSIGOD** [comment]
I have same question.Current minitouch can not support android 14+,and now,android 15 has been pushed.Hopefully, this issue will be on the agenda
